name: Build

on:
  push:
  pull_request:

jobs:
  web:
    name: Web
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/configure-pages@v2
      - run: ./build.sh
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/webroot
      - uses: actions/deploy-pages@v1
