name: Build

on:
  push:
  pull_request:

jobs:
  windows:
    name: Windows (MSVC)
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
    environment:
      name: itch
      url: https://spacemaniac.itch.io/nonexistent
  web:
    name: Web
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/configure-pages@v2
      - run: ./build.sh
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/webroot
  web-deploy:
    needs: web
    permissions:
      pages: write  # To deploy to Pages
      id-token: write  # To verify the deployment originates from an appropriate source
    environment:
      # GH recommends this environment name
      name: github-pages
      # Export the GitHub Pages URL as the environment's URL
      url: ${{ steps.deployment.outputs.page_url }}
    # Allow only one concurrent deployment
    concurrency:
      group: "pages"
      cancel-in-progress: true
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/deploy-pages@v1
      id: deployment
