name: Build

on:
  push:
  pull_request:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  web:
    name: Web
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/configure-pages@v2
        id: configure-pages
        with:
          enablement: false
      - run: ./build.sh
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/webroot
      - uses: actions/deploy-pages@v1
        if: steps.deployment.outputs.origin
        id: deployment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Allow one concurrent deployment
    concurrency:
      group: "pages"
      cancel-in-progress: true
